### ISSUE TITLE
OpenGL support

### ISSUE THREAD

**Issue by husberg-disguise** [disguise-one/RenderStream#15]
Add OpenGL support to the API

**Comment by husberg-disguise** [comment]
Logged internally as DSOF-17796

**Comment by husberg-disguise** [comment]
Should ship in r19.2 or r20.0

**Comment by medcelerate** [comment]
Is this available yet, would be great to have this for some of the tools we are building.

**Comment by josh-disguise** [comment]
It's still shipping in r20.0, not sure if there's a release date set yet but it should be in the near future.
