### ISSUE TITLE
Minimal and Schema samples do not work

### ISSUE THREAD

**Issue by ToxicBananaParty** [disguise-one/RenderStream#16]
I have not attempted to use the other two samples.

I copied and pasted the code into a new solution, compiled it to an .exe, and placed it in my RenderStream Projects folder.
Both samples compile into .exe files without issue.
The Workload immediately crashes, before any consoles with error messages can appear.

Attached are screenshots of my RenderStream Layer settings, in case it's something on my end and not the samples.
![renderstreamlayer](https://user-images.githubusercontent.com/46685109/129809119-01eca6d4-902e-428c-a734-dbc1b9baaa76.png)
![renderstreamprojects](https://user-images.githubusercontent.com/46685109/129809122-99091586-ba66-447d-acc6-a5c096cb6a3e.png)

**Comment by ToxicBananaParty** [comment]
Update: I attempted it once more using a coworker's machine as a render machine and got the following error popup from the Minimal sample: 


![Screenshot (53)](https://user-images.githubusercontent.com/46685109/129812752-b485042d-2a7f-4d4c-be61-a58d679b5307.png)

**Comment by husberg-disguise** [comment]
Can you make sure you compiled it as a 64-bit executable? We only supply the renderstream DLL as 64-bit

If that's not it, can you confirm the same issue happens with the sample's original solution? 
Maybe try running it under the debugger to see if you can narrow down what call causes the error? The executable should still run outside of d3, but will sit in the rs_awaitFrameData loop forever.

**Comment by ToxicBananaParty** [comment]
I recompiled quadruple-checking that everything was x64 and here's what we've got:

It runs fine in the debugger, seems to be stuck in that loop in the main() function as you predicted; I'm not seeing anything in the Debug Console or Event List, just constant memory usage (and it doesn't crash, haha.)

When I run just the .exe outside of disguise, it instantly quits as well (the icon of a new app appears in my task bar and instantly vanishes, that is the only indication that it has run). 

When I run it in disguise with my own machine as the render machine, the Workload instantly goes from "Launching" to "Crashed". When I run it in disguise using a coworker's machine as the render machine, it throws the same error pictured above.

**Comment by husberg-disguise** [comment]
If it goes into the loop while under the debugger, but not when run outside of disguise it sounds like it's a path/working directory issue. Minimal should open a console window (blank if no errors and stuck in the loop) and not quit straight away. 

I can take a look if you publish your source somewhere, but it'll likely just be a matter of adding a bunch of logging to do printf debugging, or adding a sleep at the start and attaching the debugger after launching through disguise. 

If you sprinkle the code with rs_logToD3 calls (https://github.com/disguise-one/RenderStream/blob/r1.27/src/include/d3renderstream.h#L319) you can see the logging inside d3 or in %localappdata%/d3/console_\<executable name\>.txt

**Comment by ToxicBananaParty** [comment]
Knowing that it works and is not launching due to user error is good enough for me, haha! Just need to study the source code for my own application, which launches fine.

Apologies if I wasted your time!

**Comment by husberg-disguise** [comment]
No worries, we appreciate all feedback. 
I'll see if I can come up with better error handling that would make it easier to diagnose similar issues.
Please let me know what the issue was when you figure it out!
