### ISSUE TITLE
Feature Request: Add support for Vulkan

### ISSUE THREAD

**Issue by mbechard** [disguise-one/RenderStream#27]
Along with the other APIs, it would be great is Vulkan was also supported as an API.
Thanks

**Comment by husberg-disguise** [comment]
Is Vulkan 1.2 ok?

Looks like we would need timeline semaphores and win32 external memory/semaphores to match dx12 capabilities.

**Comment by mbechard** [comment]
Yep that's fine, I'd want to sync using timeline semaphores. I am curious what is happening on the GPU with the texture after I hand it off though? Would it not be possible to do those operations, including the texture download, within Vulkan, to avoid API interop? Vulkan can use the transfer queues to allow for a high performance download. You should be able to interface with the mellanox API as well I'd assume.

**Comment by husberg-disguise** [comment]
We take a copy of the texture into GPGPU memory and depending on the transport (RenderStream Compressed, RenderStream Uncompressed) send it to the hardware video encoder or run our own GPGPU kernels on it before transferring it to the network card. Ideally there isn't a download to CPU memory and it gets packetized on the GPU and RDMA'd to the NIC.

It's all using asynchronous GPGPU queues already. The interop to GPGPU just lets us implement it once (or twice) instead of for each API separately.

**Comment by mbechard** [comment]
To clarify, targeting a min Vulkan 1.1 with the timeline semaphore extension instead of 1.2 is the better way to go. Everything that supports 1.1 also supports that extension on Windows, and that allows for wider GPU support.

I wonder if just doing a CUDA based interface would be better here though. That would be less work for you to maintain, and allow more control on my side.

**Comment by mbechard** [comment]
Note that there is no direct interop for Vulkan/OpenCL yet (https://github.com/KhronosGroup/Vulkan-Docs/issues/1796). So going the way of CUDA seems reasonable, since an AMD implementation should likely be Vulkan-only.

**Comment by husberg-disguise** [comment]
CUDA may happen too, but Vulkan support didn't appear to be that difficult and we like to keep our options open. 

The extensions appear to be enough. I just pushed the initial UE integration if you want to take a look at the proposed API: https://github.com/disguise-one/RenderStream-UE/commit/7153834f623b1f98ebd2eecde9e78b415fae9f61

**Comment by mbechard** [comment]
Ah cool, that was quick.
Offhand what I notice:
* It should be documented that the texture must be in GENERAL or TRANSFER_SRC layout before behind fed into sendFrame(), and will be left as that on return. Or at least document what the contract is if it's something else.
* I can see from the example you want the graphics queue. That should be documented.

* What memory barrier guarantee do you need before the call to sendFrame()? Will you execute one or will you expect the memory to be available/visible already? 
 
I'd propose that you require a guarantee that it's already been made available/visible. You should document what stage(s) you need it available/visible to.

* It seems to be lacking any sync. Vulkan will guarantee that command buffers start executing in-order of submission, but there is no guarantee they will complete in-order. There is no guarantee that execution of one command buffer will finish before the next one starts. This means right now there is nothing keeping your command buffer from starting to execute and processing the texture before my command buffer has finished filling it. Additionally, I may not want you to do your work in the same queue that my texture was last used in, so assuming any queue-level sync isn't safe.

I'd propose the the VulkanData structure also require a reference to a timeline semaphore and a timeline value, which you'd set your command buffer to wait on before beginning execution. Next, to ensure I don't start overwriting the texture before you are done with it, you should return a timeline semaphore and value that you will signal at the completion of your command buffer.  You should be able to use a single timeline semaphore to signal you are done your work with all of the input texture (maybe one that is registered during init()), as long as you ensure each command signalling on it is waiting for the previous command that was going to signal it (v=2 waits on v=1 etc.). So you are dealing with N semaphores to wait on, but only 1 for signaling when your work is done.

* Further Optimization: With the fine-grained sync we are already required to use here, you can avoid doing a copy from the Vulkan texture to a CUDA memory you own, and instead just do your first read operation directly from the texture memory. If I instead provide you with an external memory handle that you import into CUDA (using `cudaImportExternalMemory())`, along with a timeline semaphore you can import into CUDA (using `cudaImportExternalSemaphore()`), then you can just read directly from that memory. Since you are signalling a different timeline semaphore when you are done, I can start using that texture at the appropriate time, and can avoid touching that texture for more time (until another later frame) if it turns out your thread isn't done with it when I first want to start re-using it.

* Possibly this can all be handled using a single timeline semaphore, we'd just need to define when signals are happening to ensure it's always signaled in increasing order.

Thoughts?

**Comment by husberg-disguise** [comment]
That's excellent feedback, thanks! 

I'm just trying to get something working with UE's VulkanRHI abstraction. May have to drop down to regular semaphores.

**Comment by mbechard** [comment]
Waiting and signaling on timeline vs binary semaphores is very similar, just a few extra lines of code to include the timeline value for timeline semaphores. Ideally you can work in either mode, since binary semaphores wouldn't work for me. My command buffers aren't signaling binary semaphores, except for the swapchain related one.
With a workflow that supports both, I'd suggest N*2 semaphores: 1 for wait and 1 for signal, for each texture. That way the API can be the same for both workflows, just with an unused 'value' parameter in the binary semaphore mode.

**Comment by husberg-disguise** [comment]
Here's another try with a minimal sample: https://github.com/disguise-one/RenderStream/commit/ccc68267edc14af584dbfc8eab44bf3f99118f54

There are still a bunch of issues with the sample itself, but hopefully the API is ok? 
The GPGPU queue will wait for the waitSemaphore before touching the data and signal the signalSemaphore once it's done. No guarantee that the signals will be in any order though as we use multiple queues internally.

We'll keep working on the samples and documentation, but this likely won't be released for a few months and other tasks may take priority so you may see a lack of updates.

**Comment by mbechard** [comment]
Ya that looks good to me. I like that although the sample only uses one semaphore for wait/signal, you allow for two. I'll need two since the semaphore I want you to wait on isn't going to be usable for you to signal.

**Comment by husberg-disguise** [comment]
Vulkan API added in ccc68267edc14af584dbfc8eab44bf3f99118f54 will be released unless QA comes up with any issues

**Comment by mbechard** [comment]
Thanks! Can you post a pre-release build with Vulkan support at some point (or email it to me directly), so I can test the integration?

**Comment by mbechard** [comment]
Seems like we're still missing semaphores for rs_getFrameImageData though, should also have wait/signal I'd say
