### ISSUE TITLE
Add way to de-register a GL texture that is being deleted by the host process

### ISSUE THREAD

**Issue by mbechard** [disguise-one/RenderStream#29]
Since OpenGL is free to re-use a texture ID given to glDeleteTextures() as a future return value from glGenTextures(), there is no guarantee the ID given to you represents the same texture as you previously registered to the GPGPU APIs on a previous call with that particular ID.
Ideally the API should have some way for me to tell you that an ID I've previously given you is being deleted, so you can deregister it from the GPGPU API, and treat it as a new texture if you see it again.
Thanks

**Comment by josh-disguise** [comment]
Sounds sensible!

**Comment by mbechard** [comment]
FYI, I'm hitting this in live-environments. So it's not just a theoretical issue, the drivers will re-use IDs.

**Comment by husberg-disguise** [comment]
Would it be worth querying the texture's size and format each use to see if they've changed and re-register it? 

We could do that in a hotfix before any API changes (which will need to wait for a major release).

**Comment by mbechard** [comment]
I think that would be ok, I'd be happy to test and see.

**Comment by husberg-disguise** [comment]
Querying and re-registering is logged internally as DSOF-20357 and should go out in r21.0.3, here's a pre-release if you want to give it a try before April 20th:
https://cfpkg.disguise.one/S3/devx64branch/119216/x64-msvc16.0-toolset142-Release-full/d3-full-r21.0.3-88532_OpenGL-QA_x64.exe

**Comment by mbechard** [comment]
This seems to do the trick, thanks! It requires me to upgrade my headers though, even though there is 0 changes to the API other than the version number?
I'll make a new issue for that.

**Comment by husberg-disguise** [comment]
rs_releaseImage added in 2560cd16c9b7a473b717834b0ae3dbffa7ec62a5
