### ISSUE TITLE
Changing input texture not working with GL

### ISSUE THREAD

**Issue by mbechard** [disguise-one/RenderStream#33]
If my schema exposes an image, I'm able to get a correct texture out of RenderStream initially. However if I change the texture in D3, then I start getting a blank texture for the new one. No errors are returned. I get the new resolution correctly, rs_getFrameImageData() is returning correct information, and rs_getFrameImage isn't returning an error.
I confirmed in this case the textureId is changing, so it's not a side effect of #29  
Any ideas on what could be the issue?

**Comment by husberg-disguise** [comment]
Hmm, I unfortunately haven't been able to reproduce this. Can you try this patch for the OpenGL sample to see if you can recreate it?
https://gist.github.com/husberg-disguise/0df8b04a5dedd85d8f68ba653e4573ac

**Comment by husberg-disguise** [comment]
From looking at the code, the likeliest case is that the imageId passed into rs_getFrameImage is incorrect or rs_getFrameImage is called with the same id multiple twice. 

That function is a bit special with the id being a single-use reference id passed via the ImageFrameData out parameter in rs_getFrameImageData and a fallback to a 1x1 transparent black image. I'll try to add some better error reporting.

**Comment by mbechard** [comment]
Is that function filling the already allocated texture ID passed in always, or could it potentially be reallocating the texture named by that ID?

**Comment by husberg-disguise** [comment]
Just filling in the passed in texture from preallocated GPU memory.

**Comment by mbechard** [comment]
I'm also getting cases where getFrameImageData is returning a 1x1 texture with an Id of 0, but the function isn't returning a failure return value.

**Comment by husberg-disguise** [comment]
That happens when there's no input to the parameter in d3 (None/Arrow input with no arrow) or when no image data has been received on the render node yet (will be accompanied by a log statement of "Dropped input frame for key: ... stream exists: <0/1> received any: <0/1>"; caused by either a failure to prefetch or a network issue)

**Comment by mbechard** [comment]
Ok, I would expect that case to return an error code offhand.

**Comment by mbechard** [comment]
Looking at this more, I think this bug is caused by a combination of not working around the error behavior here, along with hitting #29. When the texture is changed in D3 I first get a 1x1 texture, which I was allocating, then I get the correct res on the next frame, which I then allocate. GL was giving me back the same Texture Id on the second allocation, which runs into the issue in #29. So if I handle the error case I run into this a little less, but will eventually start to hit it due to ID re-use coming out of GL.
