### ISSUE TITLE
Version compatibility needs to be maintained better

### ISSUE THREAD

**Issue by mbechard** [disguise-one/RenderStream#35]
Seems like you guys are posting new versions of the API often, which is great! However it seems like currently the API version an app is compiled against needs to match the version D3 is using exactly. Most recently 1.28 was upped to 1.29, however there was 0 API changes in the header, so it was totally unnecessary for this version change to cause incompatibility.

I understand your structs may change size/layouts in API change, but even then, those should be able kept backwards compatible at least a few versions back internally within the .dll. The app tells you what version of the header it's using, so you know the size/layout of the structs it's going to expect to work in. Your .dll should convert between those structs and the new structs internally (the old structs don't need to be kept in the public API, you just need to keep them in a private one). It should only be a few lines of code per version. Throw away support for older versions as the cases grow sure, but at things shouldn't break with every version change. This will lead to a worse user experience otherwise.

Thanks!

**Comment by husberg-disguise** [comment]
Definitely something we should do, but needs some internal policy making for it to happen.

RS1.29 was mostly behavioural changes IIRC, some functions returned new statuses (rs_beginFollowerFrame returning per-instance state changes like rs_awaitFrameData) and orthoWidth changed its meaning.
Applications compiled against RS1.28 might've worked, but RS1.29 applications using the new functionality would not have worked correctly.

**Comment by mbechard** [comment]
I would only expect it to be one direction. Applications compiled against 1.28 should be able to be loaded into D3 that is running 1.29+. I wouldn't expect an application compiled against 1.29 to work with a D3 that only knows about 1.28. It's fine for the latter case to be an error.

**Comment by husberg-disguise** [comment]
RS1.30 function signatures should be backwards compatible with RS1.29 as of f6b62b82f94b5f15160d4c5a3380cd4632260d06
